grid_map_visualization:
  ros__parameters:
    grid_map_topic: /elevation_mapping_node/elevation_map_raw
    grid_map_visualizations: [traversability_grid]
    traversability_grid:
      type: occupancy_grid
      params:
        layer: traversability
        data_min: 1.0
        data_max: 0.0